### ISSUE TITLE
Could not find map file

### ISSUE THREAD

**Issue by vibhaanshu** [dspinellis/UMLGraph#26]
I'm using below configuration 

`<groupId>org.apache.maven.plugins</groupId>                                  
        <artifactId>maven-javadoc-plugin</artifactId>                                
        <version>${maven.javadoc.plugin.version}</version>                                                       
        <configuration>
          <aggregate>true</aggregate>
          <doclet>org.umlgraph.doclet.UmlGraphDoc</doclet>                         
          <docletArtifact>                                                         
            <groupId>org.umlgraph</groupId>                                      
            <artifactId>umlgraph</artifactId>                                    
            <version>5.6</version>                                               
          </docletArtifact>`                                                        

The warning message coming while running mvn site is ..

`[WARNING] Ensure that dot is in your path and that its path does not contain spaces
[WARNING] java.io.IOException: Cannot run program "dot": CreateProcess error=2, The system cannot find the file specified
[WARNING] at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
[WARNING] at java.lang.Runtime.exec(Runtime.java:617)
[WARNING] at java.lang.Runtime.exec(Runtime.java:485)
[WARNING] at org.umlgraph.doclet.UmlGraphDoc.runGraphviz(UmlGraphDoc.java:144)
[WARNING] at org.umlgraph.doclet.UmlGraphDoc.generateContextDiagrams(UmlGraphDoc.java:126)
[WARNING] at org.umlgraph.doclet.UmlGraphDoc.start(UmlGraphDoc.java:68)
[WARNING] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[WARNING] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[WARNING] at java.lang.reflect.Method.invoke(Method.java:606)
[WARNING] at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:280)
[WARNING] at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:160)
[WARNING] at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:397)
[WARNING] at com.sun.tools.javadoc.Start.begin(Start.java:167)
[WARNING] at com.sun.tools.javadoc.Main.execute(Main.java:59)
[WARNING] at com.sun.tools.javadoc.Main.main(Main.java:49)
[WARNING] Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified`

Looking for solution I found below link -

https://issues.apache.org/jira/browse/MJAVADOC-136

Is this the fix, if yes, how to use it with same 'mvn site' command?

**Comment by dspinellis** [comment]
Please ensure that GraphViz is installed and that you can execute `dot` from the command line.
